import copy
import logging
from typing import Any

from slime.utils.data import Dataset
from slime.utils.mask_utils import MultiTurnLossMaskGenerator
from slime.utils.processing_utils import load_processor, load_tokenizer
from slime.utils.types import Sample

__all__ = ["generate_rollout", "eval_rollout"]

logger = logging.getLogger(__name__)

TOKENIZER = None
PROCESSOR = None
MASK_GENERATOR = None
SAMPLE_PRINTED = False
EVAL_PROMPT_DATASET = {}
EVAL_PROCESSED_SAMPLES = {}  # Cache for processed evaluation samples

def eval_rollout(args, rollout_id: int) -> dict[str, dict[str, list[Any]]]:
    """Generate SFT-style evaluation data for multiple datasets.

    Args:
        args: The argument namespace
        rollout_id: The rollout iteration id

    Returns:
        A dict mapping dataset names to {"samples": processed_samples}
    """
    global TOKENIZER, PROCESSOR, MASK_GENERATOR
    if TOKENIZER is None:
        TOKENIZER = load_tokenizer(args.hf_checkpoint, trust_remote_code=True)
    if PROCESSOR is None:
        PROCESSOR = load_processor(args.hf_checkpoint, trust_remote_code=True)
    if MASK_GENERATOR is None:
        MASK_GENERATOR = MultiTurnLossMaskGenerator(TOKENIZER, tokenizer_type=args.loss_mask_type)

    results = {}
    for i in range(0, len(args.eval_prompt_data), 2):
        name, path = args.eval_prompt_data[i : i + 2]
        logger.info(f"Loading eval dataset: {name}...")
        results.update(eval_rollout_single_dataset(args, rollout_id, name, path))
    return results

def eval_rollout_single_dataset(
    args, rollout_id: int, name: str, path: str
) -> dict[str, dict[str, list[Any]]]:
    """Generate SFT-style evaluation data for a single dataset.

    Args:
        args: The argument namespace
        rollout_id: The rollout iteration id
        name: Dataset name
        path: Path to the dataset file

    Returns:
        A dict mapping dataset name to processed samples
    """
    global EVAL_PROMPT_DATASET, EVAL_PROCESSED_SAMPLES

    # Return cached samples if already processed
    if name in EVAL_PROCESSED_SAMPLES:
        logger.info(f"Using cached processed samples for {name}")
        return {name: {"samples": EVAL_PROCESSED_SAMPLES[name]}}

    # Load dataset if not already loaded
    if name not in EVAL_PROMPT_DATASET:
        logger.info(f"Loading dataset {name} from {path}")
        EVAL_PROMPT_DATASET[name] = Dataset(
            path,
            tokenizer=TOKENIZER,
            processor=PROCESSOR,
            max_length=args.rollout_max_prompt_len,
            prompt_key=args.input_key if args.eval_input_key is None else args.eval_input_key,
            label_key=args.label_key if args.eval_label_key is None else args.eval_label_key,
            multimodal_keys=args.multimodal_keys,
            metadata_key=args.metadata_key,
            tool_key=args.tool_key if args.eval_tool_key is None else args.eval_tool_key,
            apply_chat_template=args.apply_chat_template,
        )

    dataset = EVAL_PROMPT_DATASET[name]

    samples = []
    prompt_samples = dataset.samples
    sample_index = 0
    for prompt_sample in prompt_samples:
        group = []
        for _ in range(args.n_samples_per_prompt):
            sample = copy.deepcopy(prompt_sample)
            sample.index = sample_index
            sample_index += 1
            group.append(sample)
        samples.append(group)

    # Process each sample to generate tokens and loss_mask
    for sample in samples:
        (sample,) = sample
        messages = sample.prompt
        token_ids, loss_mask = MASK_GENERATOR.get_loss_mask(messages)
        response_length = MASK_GENERATOR.get_response_lengths([loss_mask])[0]

        sample.tokens = token_ids
        sample.response_length = response_length
        sample.reward = 0
        sample.loss_mask = loss_mask[-response_length:]

    # Flatten sample list
    while isinstance(samples[0], list):
        samples = sum(samples, [])

    # Trim samples to match batch size
    eval_batch_size = args.eval_batch_size or args.global_batch_size
    if eval_batch_size and len(samples) % eval_batch_size != 0:
        trim_len = (len(samples) // eval_batch_size) * eval_batch_size
        origin_data_length = len(samples)
        samples = samples[:trim_len]
        logger.info(f"Trimmed eval samples from {origin_data_length} to {trim_len}")

    # Cache processed samples
    EVAL_PROCESSED_SAMPLES[name] = samples

    return {name: {"samples": samples}}

def generate_rollout(args, rollout_id, data_buffer, evaluation=False):
    """An example to implement the generate_rollout function for an rule based rm rollout generation.

    Args:
        args: the whole args
        rollout_id: int, the id of the rollout, used for deterministic data generation
        data_buffer: the data buffer to store the generated samples
        evaluation: bool, whether the rollout is for evaluation or not

    Returns:
        list[Sample]: a list of samples generated by the rollout
    """
    assert args.rollout_global_dataset

    # Handle SFT-style evaluation (PPL computation)
    if evaluation:
        return eval_rollout(args, rollout_id)

    global TOKENIZER, PROCESSOR, MASK_GENERATOR, SAMPLE_PRINTED
    if TOKENIZER is None:
        TOKENIZER = load_tokenizer(args.hf_checkpoint, trust_remote_code=True)

    if PROCESSOR is None:
        PROCESSOR = load_processor(args.hf_checkpoint, trust_remote_code=True)

    if MASK_GENERATOR is None:
        MASK_GENERATOR = MultiTurnLossMaskGenerator(TOKENIZER, tokenizer_type=args.loss_mask_type)

    samples = data_buffer.get_samples(args.rollout_batch_size)

    for i, sample in enumerate(samples):
        (sample,) = sample
        messages = sample.prompt
        tools = sample.metadata.get("tools", None)

        token_ids, loss_mask = MASK_GENERATOR.get_loss_mask(messages, tools=tools)

        response_length = MASK_GENERATOR.get_response_lengths([loss_mask])[0]

        sample.tokens = token_ids
        sample.response_length = response_length
        sample.reward = 0
        sample.loss_mask = loss_mask[-response_length:]

        if i == 0 and not SAMPLE_PRINTED:
            logger.info(
                f"sft_rollout::generate_rollout example data: {sample=} (raw){messages=} (raw){token_ids=} (raw){loss_mask=} {response_length=}"
            )
            SAMPLE_PRINTED = True

    return samples
